### ISSUE TITLE
navbar to external sites

### ISSUE THREAD

**Issue by leoneln** [leonelnieto/UDOTDB#1]
The the following menu items to the top nav bar
1. Strategic Direction
2. UDOT Home Page

The menu bar should collapse on mobile devises. Double check bootstrap documentation for that.

**Comment by daniellabirch** [comment]
Do you want the UDOT logo to lead to the UDOT Home Page?

**Comment by daniellabirch** [comment]
Including a link to the Strategic Direction page: http://www.udot.utah.gov/strategic-direction/

**Comment by leoneln** [comment]
Navbar defaults to collapse now, sweet.. Thanks

**Comment by daniellabirch** [comment]
The UDOT logo now leads to the UDOT Home Page.

**Comment by daniellabirch** [comment]
the navbar and link(s) have been added

**Comment by daniellabirch** [comment]
the navbar and link(s) have been added
