### ISSUE TITLE
Prod, Dev, and Deploy

### ISSUE THREAD

**Issue by leoneln** [leonelnieto/UDOTDB#2]
Production:
We need to deploy this to udot.utah.gov/dashboard/
Also create a folder with password protected under udot.utah.gov/dashboard/internal
Version Control: Github Pages and Github
Development: Currently a copy of this site is running here http://maps.udot.utah.gov/wadocuments/Apps/UDOTDB/
Once we have it deployed in udot.utah.gov we need to remove this and add a redirect script just in case anyone is using this link.

**Comment by daniellabirch** [comment]
This is pretty much ready to deploy so I will continue development in Subversion. There are still some tweaks to make sure that the links are all working on every page but this will have to be fine tuned in the testing environment.

**Comment by daniellabirch** [comment]
@leoneln, this has been deployed to subversion. From now on, all changes must be made and tracked in subversion.

**Comment by daniellabirch** [comment]
@leoneln, this has been deployed to subversion. From now on, all changes must be made and tracked in subversion.
