### ISSUE TITLE
templating nav bars

### ISSUE THREAD

**Issue by daniellabirch** [leonelnieto/UDOTDB#4]
create a template to include sidebar and top bar

**Comment by leoneln** [comment]
Hey, is this going to work with mustash.js?

**Comment by daniellabirch** [comment]
Decided to go with a different strategy because mustache.js still has xss vulnerabilities. I decided instead to use javascript template literals to include sidebar and Content Security Policy to prevent cross-site-scripting attacks in the future. I've merged this code now so I'm going to close this issue.

**Comment by daniellabirch** [comment]
Decided to go with a different strategy because mustache.js still has xss vulnerabilities. I decided instead to use javascript template literals to include sidebar and Content Security Policy to prevent cross-site-scripting attacks in the future. I've merged this code now so I'm going to close this issue.
